"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/NavBar";
import Footer from "@/Components/Shared/Footer";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/Provider/NextAuthProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "FrostUI",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/icon/icon.png",
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="frostUILight">
      <body>
        <NextAuthProvider>
          <Navbar></Navbar>
          <div className="min-h-screen ">{children}</div>
          <Footer></Footer>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </NextAuthProvider>
      </body>
    </html>
  );
}
