import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../CSS/theme.css";
import "../CSS/custombg.css";
import "../CSS/otherStyle.css";
import LayoutClient from "./LayoutClient.jsx";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "FrostUI",
  description: "Generated by create next app",
  icons: {
    icon: "/icon/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="frostUILight">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
